// Explicit icon registry — importing only what the UI uses keeps lucide
// tree-shakeable instead of pulling the entire icon set into the bundle.
import {
  Anchor,
  ArrowDownLeft,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRightCircle,
  ArrowUpRight,
  BarChart3,
  Bell,
  Box,
  Building2,
  Calculator,
  ChartNoAxesColumn,
  Check,
  CheckCircle2,
  ChevronRight,
  Circle,
  Clock,
  Coins,
  Container,
  Database,
  Eye,
  EyeOff,
  FileCheck,
  FileDown,
  FilePlus2,
  FileSignature,
  FileText,
  Folder,
  GitCompareArrows,
  Globe,
  Info,
  KeyRound,
  Layers,
  LayoutDashboard,
  Library,
  ListChecks,
  Loader,
  Lock,
  Mail,
  MailCheck,
  MapPin,
  MessageSquarePlus,
  Package,
  PanelLeft,
  PanelLeftClose,
  Paintbrush,
  Palette,
  Paperclip,
  Pencil,
  Phone,
  Plane,
  Play,
  Plus,
  Printer,
  Radar,
  Receipt,
  Scale,
  ScanText,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Ship,
  SlidersHorizontal,
  Star,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Truck,
  User,
  UserPlus,
  Wallet,
  Workflow,
  X,
} from 'lucide-vue-next'

export const icons = {
  'anchor': Anchor,
  'arrow-down-left': ArrowDownLeft,
  'arrow-left': ArrowLeft,
  'arrow-left-right': ArrowLeftRight,
  'arrow-right-circle': ArrowRightCircle,
  'arrow-up-right': ArrowUpRight,
  'bar-chart-3': BarChart3,
  'bell': Bell,
  'box': Box,
  'building-2': Building2,
  'calculator': Calculator,
  'chart-no-axes-column': ChartNoAxesColumn,
  'check': Check,
  'check-circle-2': CheckCircle2,
  'chevron-right': ChevronRight,
  'circle': Circle,
  'clock': Clock,
  'coins': Coins,
  'container': Container,
  'database': Database,
  'eye': Eye,
  'eye-off': EyeOff,
  'file-check': FileCheck,
  'file-down': FileDown,
  'file-plus-2': FilePlus2,
  'file-signature': FileSignature,
  'file-text': FileText,
  'folder': Folder,
  'git-compare-arrows': GitCompareArrows,
  'globe': Globe,
  'info': Info,
  'key-round': KeyRound,
  'layers': Layers,
  'layout-dashboard': LayoutDashboard,
  'loader': Loader,
  'lock': Lock,
  'library': Library,
  'list-checks': ListChecks,
  'mail': Mail,
  'mail-check': MailCheck,
  'map-pin': MapPin,
  'message-square-plus': MessageSquarePlus,
  'package': Package,
  'paintbrush': Paintbrush,
  'palette': Palette,
  'panel-left': PanelLeft,
  'panel-left-close': PanelLeftClose,
  'paperclip': Paperclip,
  'pencil': Pencil,
  'phone': Phone,
  'plane': Plane,
  'play': Play,
  'plus': Plus,
  'printer': Printer,
  'radar': Radar,
  'receipt': Receipt,
  'scale': Scale,
  'scan-text': ScanText,
  'search': Search,
  'send': Send,
  'settings': Settings,
  'shield-check': ShieldCheck,
  'ship': Ship,
  'sliders-horizontal': SlidersHorizontal,
  'star': Star,
  'trash-2': Trash2,
  'trending-up': TrendingUp,
  'triangle-alert': TriangleAlert,
  'truck': Truck,
  'user': User,
  'user-plus': UserPlus,
  'wallet': Wallet,
  'workflow': Workflow,
  'x': X,
}
